language: go
script: go test -race -cpu 1,2,4 -v -timeout 5m ./...
sudo: false
go:
  - 1.3.3
  - 1.4.2
  - 1.5.1
  - tip
matrix:
  allow_failures:
    - go: tip
notifications:
    on_success: "change"  # options: [always|never|change] default: always
    on_failure: "always"  # options: [always|never|change] default: always
    on_start: false     # default: false